font_family Hack Nerd Font
font_size 12.5

cursor_shape block
cursor_blink_interval 0.7
background_opacity 0.85


# BEGIN_KITTY_THEME
# Box
include current-theme.conf
# END_KITTY_THEME

window_padding_width 10
