
#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = AQ_DRM_DEVICES,/dev/dri/card1
env = XCURSOR_THEME, Breeze_Dark_Lime
env = HYPRCURSOR_THEME, Breeze_Dark_Lime