general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 300
    on-resume = notify-send -t 500 "Welcome back"
    on-timeout = sh -c 'playerctl status 2>/dev/null | grep -q Playing || hyprlock'
}
